### ISSUE TITLE
Broken link on PyPI-page pandas-schema

### ISSUE THREAD

**Issue by chrispijo** [multimeric/PandasSchema#59]
I am not sure if this is the place but I mention it anyway. 

There is a broken link on the PyPI-page of `pandas-schema`. It still links to https://tmiguelt.github.io/PandasSchema/ while it should link to https://multimeric.github.io/PandasSchema/.

**Comment by multimeric** [comment]
Yep, good catch. That's due to me recently changing my username. It's fixed in the readme but won't be fixed on PyPi until I push a new release.

**Comment by hemi-hga** [comment]
@multimeric should be fixed now
