### ISSUE TITLE
Question: Does DateFormatValidation support multiple date format strings?

### ISSUE THREAD

**Issue by pranshuag9** [multimeric/PandasSchema#62]
There is a usecase where i want to support multiple date formats in a column. How can this be done using PandasSchema. Only workaround i can think of right now is to write whole logic inside CustomElementValidation but it will be better if this functionality is provided by PandasSchema. If it is already present, how to use it?

**Comment by multimeric** [comment]
You should be able to do this using boolean logic: https://multimeric.github.io/PandasSchema/#boolean-logic-on-validators

**Comment by pranshuag9** [comment]
thanks for quick reply. Boolean logic is great. Fixed the issue.
